### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by inbarbuzaglo** [inbarbuzaglo/C-MATALA-0#3]
שימי לב כי אנחנו צריכות לעדכן את כל השינויים שבצענו במחלקות טרם ההגשה , הסבר כללי ומתומצת למחלקות החדשות שיצרנו במטלה 3

**Comment by inbarbuzaglo** [comment]
עדכנתי בread me הסברים על המחלקות algo,algo2

נשאר לעשות README למחלקות הבאות -
1. WeightedMean
2. line_OUTPUT_FORMAT

**Comment by Meyt3893** [comment]
I update the explanations about line output format and weightedmean classes in README
