### ISSUE TITLE
javadoc

### ISSUE THREAD

**Issue by inbarbuzaglo** [inbarbuzaglo/C-MATALA-0#4]
יש לבצע תיעוד והסבר לכל מחלקה שיהיה ברור למי שיקרא את הקוד מה המחלקה מבצעת בדיוק , כרגע זה לא מספיק מובן וברור. יש לשפר זאת בהקדם

**Comment by inbarbuzaglo** [comment]
עשיתי java doc למחלקות של algo ,algo2,

נותרו לעשות javadoc במחלקות הבאות -
1. lineoutput format
2. weightedMean
לא לשכוח לעשות קומיטים בקוד שהעלנו של מחלקות אלו

**Comment by Meyt3893** [comment]
I added explanations to this classes and I did commits.
we should produce new javadoc file (to keep it updated)
