### ISSUE TITLE
opning more packages

### ISSUE THREAD

**Issue by Meyt3893** [inbarbuzaglo/C-MATALA-0#8]
our Dividing to packages is not correct. we should opning more packages and inserting the rellevant classes to the new packages.

**Comment by inbarbuzaglo** [comment]
I agree , i did it this way , tell me what you think -
1. Algo package-
the classes ; Algo ,Algo2, Weightedmean,line_OUTPUT_FORMAT
2. Headline_Obj package-
line , Position , Startline ,WifiData
3. KML package-
Filter,toKML
4. CSV package-
CSV,listFromCSV,Main
5. test package-
all the tests of Junit

for now i divided to 5 packages tell me what you think

**Comment by Meyt3893** [comment]
I think we should:
1. splite KML package to KML package (toKML) and Filter package(include filter classes- we should splite filter class to 2 classes- each filter in another class, see the rellevant issue)
2. set hedline_obj package to "Scanning" package
3.line output format- should be in "Scanning" package

**Comment by inbarbuzaglo** [comment]
I agree , accept the filter seperated from the package of toKML-  because the filter is relevant just to the kml class , thats why I think it should be united with the kml

**Comment by inbarbuzaglo** [comment]
pay attention I did the commits in the classes like we agreed
